config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def edit
  end

  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to @flat, notice: 'Flat is created.'
    else
      render :new
    end
  end

  def update
    if @flat.update(flat_params)
      redirect_to @flat, notice: 'Flat is updated.'
    else
      render :edit
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_url, notice: 'Flat is deleted.'
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def flat_params
      params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<div class="container">
  <h1>Edit Flat</h1>
  <%= render 'form', flat: @flat %>

  <%= link_to 'Show', @flat %> |
  <%= link_to 'Back', flats_path %>
</div>

app/views/flats/index.html.erb
<div class="container">
<div class="row">
  <div class="col-12">
    <h1><strong>Flats</strong></h1>
  </div>
</div>

<div class="row">
  <% @flats.each do |flat| %>
  <div class="col-4">
    <div class="card">
      <div class="flat-card-image" style="background-image: url('https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200')"></div>
      <div class="card-content">
        <h4> <%= link_to flat.name, flat, class: "name" %> </h4>
        <p> <%= flat.address %> </p>
        <p> <%= flat.description %> </p>
        <div class="icons">
          <p> <i class="fas fa-euro-sign"></i> <%= flat.price_per_night %> </p>
          <p> <i class="fas fa-user-friends"></i> <%= flat.number_of_guests %> </p>
          <%= link_to flat, method: :delete, data: { confirm: 'Are you sure?' } do%>
          <i class="fas fa-trash"></i>
          <% end %>
        </div>
      </div>
      </div>
    </div>
  <% end %>
</div>

  <%= link_to 'New Flat', new_flat_path, class: "btn btn-primary" %>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h1>New Flat</h1>

  <%= render 'form', flat: @flat %>

  <%= link_to 'Back', flats_path %>
</div>

app/views/flats/show.html.erb
<div class="container">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200');">
    <div class="container">
      <h1><%= @flat.name %></h1>
      <a class="btn btn-danger" href="#">Book</a>
    </div>
  </div>
  <div class="card-product">
  <div class="card-product-infos">
    <h2>Address: <%= @flat.address %> </h2>
    <p><%= @flat.description %></p>
       <p>
      <strong>Price per Night:</strong>
      <%= @flat.price_per_night %>
    </p>
    <p>
      <strong>Number of Guests:</strong>
      <%= @flat.number_of_guests %>
    </p>
  </div>
</div>




  <%= link_to 'Edit', edit_flat_path(@flat) %> |
  <%= link_to 'Back', flats_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>